services:
  app:
    build:
      context: .
    container_name: linkut-app
    env_file: ./.env
    environment:
      CONVERT_SHORT_TO_ORGINAL_URL_ENDPOINT: ${CONVERT_SHORT_TO_ORGINAL_URL_ENDPOINT}
      SEED_USERS_PASSWORD: ${SEED_USERS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
